-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 13, 2021 at 11:12 PM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `prem_search`
--

-- --------------------------------------------------------

--
-- Table structure for table `player`
--

CREATE TABLE `player` (
  `id` int(4) NOT NULL,
  `playerName` varchar(255) NOT NULL,
  `image` text NOT NULL,
  `shirtNum` int(2) NOT NULL,
  `description` longtext NOT NULL,
  `team_id` int(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `player`
--

INSERT INTO `player` (`id`, `playerName`, `image`, `shirtNum`, `description`, `team_id`) VALUES
(1, 'Cristiano Ronaldo', 'https://idsb.tmgrup.com.tr/ly/uploads/images/2021/09/12/143856.jpg', 7, 'Portuguese footballer Cristiano Ronaldo is often regarded as one of the best footballers to have ever played the game and his performances over the better part of a decade have only helped in reinforcing that belief among football fans. Ronaldo grew up in Madeira, Portugal but after graduating from the youth set up at Sporting CP he was immediately snapped up by English club Manchester United after his talent as a winger was spotted by their legendary manager Sir Alex Ferguson. Ronaldo spent six years at Manchester United and that was where he developed his game as a skillful, quick, lethal winger who could score goals and create opportunities for his team mates. He won plenty of trophies for Manchester United and also shone for the Portugual before he moved to Real Madrid as the world’s most expensive player. At Real Madrid he has broken some of the most important goal scoring record that had stood for many years and also led the club to important trophies. Ronaldo is also the captain of the Portuguese national team and led them to victory in Euro 2016—their first-ever triumph in a major tournament. He has also won plenty of individual awards that have further cemented his status as one of the world’s premier footballers', 1),
(2, 'Bruno Fernandes', 'https://www.thesun.co.uk/wp-content/uploads/2021/02/14f68752-ef30-433c-828d-152cda3deac6.jpg', 18, 'On 29 January 2020, English club Manchester United agreed with Sporting to buy Fernandes. This was for a fee of up to €80 million (£67.6 million). Fernandes also needed to pass a medical and agree personal terms. The transfer was officially done the day after. The initial fee is around €55 million (£47 million), and up to €25 million (£21 million) in add-ons. Sporting will also get 10% of the profits if United ever sell Fernandes. Fernandes signed a five-and-a-half-year contract.\r\n\r\nHe made his debut on 1 February. He played the full 90 minutes of a 0-0 draw at home to Wolverhampton Wanderers. In Manchester United\'s 2–0 away win over Chelsea on 17 February, he made an assist for the second goal. This was a cross for a header from Harry Maguire. Fernandes came on as a late substitute for Manchester United against Club Brugge in a 1–1 draw. This was his European debut for the club. He scored his first goal for Manchester United against Watford on 23 February. This was a penalty in a 3–0 victory at Old Trafford. In this match, he also made an assist for the third goal scored by Mason Greenwood. His first European goal for the club was in the second leg of their UEFA Europa League round of 32 tie against Club Brugge at Old Trafford. Fernandes scored a penalty. This helped Manchester United to win 5–0. On 16 March 2020, Fernandes was voted as the Premier League Player of the Month for February. On 30 June 2020, Fernandes scored his first brace (two goals in one match) for the club in a 3–0 win against Brighton & Hove Albion. In June 2020, he won awards for the club and in the Premier League. This included winning the Premier League Player of the Month and Goal of the Month. He became the first player to win both awards at the same time in the Premier League. He also became the first Manchester United player to win the Premier League Player of the Month award two months in a row since Cristiano Ronaldo in the 2006–07 season. Bruno Fernandes has scored 8 goals and assisted 7 times in 14 games in his Premier League first season with Manchester United.', 1),
(3, 'Marcus Rashford ', 'https://www.thesun.co.uk/wp-content/uploads/2021/10/NINTCHDBPICT000690329045.jpg', 10, 'Marcus Rashford MBE (born 31 October 1997) is an English footballer. He plays as a forward for Manchester United and the England national team. Rashford has been with Manchester United since he was seven years old. He made his debut for the first team in 2016 in a game against Midtjylland. He scored two goals in that game, and two more in his next game against Arsenal. Rashford also scored in his first game for the England national team in May 2016.\r\n\r\nRashford also campaigns on issues of child food poverty and literacy in the UK. Rashford was awarded Member of the Order of the British Empire for his charity work. In addition, he was also awarded an honorary doctorate from the University of Manchester.', 1),
(4, 'Paul Pogba', 'https://d2x51gyc4ptf2q.cloudfront.net/content/uploads/2021/11/08193215/Man-United-star-Paul-Pogba.jpg', 6, 'Paul Pogba is a French footballer who plays for the national French team and the ‘English Premier League’ club ‘Manchester United.’ Back in 2016, when he made his return to ‘Manchester United,’ Paul became the most expensive footballer in the world. He began his professional football career with ‘Manchester United’ in 2011 and was loaned to the Italian club ‘Juventus’ the very next year. His roaring performance had his team embarking on a winning streak with four consecutive ‘Serie A’ titles, two ‘Supercoppa Italiana,’ and two ‘Coppola Italia.’ His consistently brilliant performance made him the most promising young football player, and in 2013, he was honored with the ‘Golden Boy’ award. He was included in the 2015 ‘UEFA Team of the Year,’ as he played a decisive role in ensuring his team ended up as the runner-up in the 2015 ‘UEFA Champions League.’ In 2013, he led his national French football team to the title win in the ‘FIFA Under-20 World Cup.’ He also went home with the ‘Best Player’ award at the end of the tournament. In the 2014 ‘FIFA World Cup,’ he was named the ‘Best Young Player’ of the tournament.', 1),
(5, 'Romelu Lukaku', 'https://i2-prod.dailystar.co.uk/incoming/article25239126.ece/ALTERNATES/s615b/0_GettyImages-1235921513jp.jpg', 9, 'Romelu Lukaku is a Belgian footballer who plays for the Belgian national team along with the ‘Premier League’ team ‘Manchester United.’ Born and raised in Antwerp, Belgium, Romelu started playing football at a young age and joined his first club, ‘Rupel Boom,’ at the age of 5. Eventually, he was discovered by a bigger club, ‘Lierse’ and was inducted into their youth program. He scored 121 goals in the 68 matches that he played for ‘Lierse’, which got him a contract with ‘Anderlecht.’ Soon, he emerged as the lead scorer in the ‘Belgian Championship.’ Following this, he joined ‘Chelsea’ in 2011. In 2012, he was loaned to ‘West Bromwich Albion.’ In 2014, he signed a three-year contract with ‘Everton.’ After a lot of speculations, he signed a five-year contract with ‘Manchester United,’ in 2017. Romelu has played for the Belgian ‘Under-21’ team and the Belgian senior team. Romelu happens to be a very aggressive player on the field and is known to use his body to get around the defenders.', 2),
(6, 'N\'golo Kante', 'https://image.assets.pressassociation.io/v2/image/production/ad1477126288f98477f41055c96451a0Y29udGVudHNlYXJjaGFwaSwxNjMzNzkyMjU3/2.62639284.jpg?rect=0,94,2873,1616&ext=.jpg', 7, 'N\'Golo Kanté (born 29 March 1991) is a French professional footballer who plays as a central midfielder for Premier League club Chelsea and the France national team.[4] Considered by many to be one of the world\'s best midfielders, Kanté is widely praised for his work rate and defensive acumen.\r\n\r\nKanté made his senior professional debut with Boulogne in 2012, appearing as a substitute in one Ligue 2 match, and played an entire season in the third division the following year. After that he joined Ligue 2 side Caen on a free transfer, finished third and won promotion to Ligue 1. He stayed with the club for one more year.\r\n\r\nIn 2015, Kanté joined Leicester City for a fee worth £5.6 million and was integral to their maiden Premier League victory. The following year, he joined Chelsea for a fee worth £32 million and again won the league, making him the first outfield player to win consecutive English league titles with different clubs since Eric Cantona in 1992 and 1993. He has also won the PFA Players\' Player of the Year and FWA Footballer of the Year, an FA Cup, the UEFA Europa League, and the UEFA Champions League. He was named the UEFA Men\'s Midfielder of the year in 2021.\r\n\r\nKanté made his senior international debut for France in 2016 and was included in the squad that finished runners-up at the 2016 European Championship. In 2017 Kanté was named the French Player of the Year, a first for a player from the Premier League in seven years, and twelve months later was a key member of the 2018 FIFA World Cup winning squad.', 2),
(7, 'Thiago Silva ', 'https://www.thesun.co.uk/wp-content/uploads/2021/09/dba1e778-6ddf-469c-a99f-4ecc3492212d.jpg', 6, 'Thiago Emiliano da Silva (born 22 September 1984) is a Brazilian professional footballer who plays as a centre back for Premier League club Chelsea and captains the Brazil national team. He is regarded as one of the best defenders of his generation.\r\n\r\nSilva began his senior club career in 2002 playing as a midfielder for RS Futebol, and transitioned to a defensive position while at Juventude; he then signed with Porto in 2004, at age 19, and moved to Dynamo Moscow on loan, where he was hospitalized with a near fatal bout of tuberculosis. After recovering, he joined Fluminense and won a Copa do Brasil. In 2009, Silva moved to AC Milan for a reported fee of €8 million and won a Serie A title.\r\n\r\nIn 2012, Silva was the subject of a then-record association football transfer when he signed for Paris Saint-Germain in a transfer worth up to €42 million, becoming the most expensive defender ever at the time. There, he won seven Ligue 1 titles, six Coupes de la Ligue, five Coupes de France, and reached the 2020 UEFA Champions League Final. Silva holds the record as the club\'s longest ever serving captain and ranks eight-highest all-time for appearances. In 2020, he signed for Chelsea on a free transfer, and won the UEFA Champions League in his first season at the club.', 2),
(8, 'Mason Mount ', 'https://i2-prod.mirror.co.uk/incoming/article25484763.ece/ALTERNATES/s615b/2_GettyImages-1348940174.jpg', 19, 'Mason Tony Mount (born 10 January 1999) is an English professional footballer who plays as an attacking or central midfielder for Premier League club Chelsea and the England national team.\r\n\r\nMount began his senior club career with Chelsea, and joined Vitesse and Derby County on consecutive loans between 2017 and 2019. He established himself as an integral player for Chelsea in the following years, and won the UEFA Champions League and the UEFA Super Cup in 2021.\r\n\r\nMount won the UEFA European Under-19 Championship with the England national under-19 team in 2017. He made his senior international debut in 2019, at age 20, and was part of the England team at UEFA Euro 2020.', 2),
(9, 'Mohammed bin salem', 'https://e0.365dm.com/21/10/2048x1152/skysports-mohamed-mo-salah_5555663.jpg', 11, 'Mohamed Salah Hamed Mahrous Ghaly (born 15 June 1992), also known as Mo Salah, is an Egyptian professional footballer who plays as a forward for Premier League club Liverpool and captains the Egypt national team. Considered one of the best players in the world, he is known for his finishing, dribbling, and speed.\r\n\r\nSalah started his senior career in 2010 playing for Al Mokawloon, departing in 2012 to join Basel, where he won two Swiss Super League titles. In 2014, Salah joined Chelsea for a reported fee of £11 million, but limited gametime led to successive loans to Fiorentina and Roma, who later signed him permanently for €15 million. In 2017, Salah was the subject of a then-club record association football transfer when he signed for Liverpool for £36.9 million, becoming the most expensive Egyptian player of all time. There, Salah won the Premier League, the UEFA Champions League, the Premier League Golden Boot twice, and finished third for the Best FIFA Men\'s Player in 2018. He also holds the record for most Premier League goals scored (32) in a 38-game season, and ranks as Liverpool\'s tenth-highest all-time top goalscorer.', 5),
(10, 'Sadio Mane ', 'https://www.bordercountiesadvertizer.co.uk/resources/images/11243364.jpg?display=1&htype=0&type=responsive-gallery', 10, 'Sadio Mané (born 10 April 1992) is a Senegalese professional footballer who plays as a winger for Premier League club Liverpool and the Senegal national team. Mané finished fourth for the 2019 Ballon d\'Or, and in the award for the Best FIFA Men\'s Player he ranked fifth in 2019 and fourth in 2020.\r\n\r\nMané began his professional career with Ligue 2 club Metz at age 19, but he departed after a solitary season to join Austrian club Red Bull Salzburg in 2012 for a fee of €4 million, winning a league and cup domestic double in the 2013–14 season. Later that summer, Mané transferred to English club Southampton for a club record fee of £11.8 million. There, he set a new Premier League record for the fastest hat-trick, scored in 176 seconds in a 6–1 win over Aston Villa in 2015.\r\n\r\nHe signed for fellow Premier League side Liverpool in 2016, for a reported fee of £34 million. With Liverpool, Mané helped them reach back-to-back UEFA Champions League Finals in 2018 and 2019, winning the latter. He also finished as the league\'s joint-top goalscorer in the 2018–19 season, winning the Premier League Golden Boot. Mané then helped end Liverpool\'s 30 year league title drought by winning the 2019–20 Premier League. In October 2021 he scored his 100th Premier League goal, becoming the third African to reach the landmark.', 5),
(11, 'Roberto Firmino ', 'https://www.si.com/.image/t_share/MTg1NDgwNDA0MzgyMjYyNDMz/bobby.jpg', 9, 'Roberto Firmino Barbosa de Oliveira (born 2 October 1991) is a Brazilian professional footballer who plays as a forward or attacking midfielder for Premier League club Liverpool and the Brazil national team.\r\n\r\nAfter starting his career with Figueirense in 2009, he spent four-and-a-half seasons at Hoffenheim. His 16 goals in 33 games for the 2013–14 Bundesliga season earned him the award for the league\'s Breakthrough Player. In July 2015, he signed for Liverpool. His creativity, goalscoring and work rate have earned him plaudits at Liverpool, with manager Jürgen Klopp referring to Firmino as the \"engine\" that propels the club\'s counter-attacking system. In the 2018–19 season he won the UEFA Champions League, and the following season won the UEFA Super Cup, the FIFA Club World Cup after scoring the winner in the final, and the 2019–20 Premier League title, Liverpool\'s first league title in 30 years.\r\n\r\nFirmino made his international debut for Brazil in November 2014. He represented the nation at the 2015 Copa América, the 2018 FIFA World Cup, the 2019 Copa América and the 2021 Copa América.', 5),
(12, 'Virgil Van Dick', 'https://d3nfwcxd527z59.cloudfront.net/content/uploads/2021/11/23122100/Virgil-van-Dijk-Liverpool1.jpg', 4, 'Virgil van Dijk (born 8 July 1991) is a Dutch professional footballer who plays as a centre-back for Premier League club Liverpool and the Netherlands national team. Considered one of the best defenders in the world,[4] Van Dijk is known for his strength, leadership and aerial ability. He is the only defender to win UEFA Men\'s Player of the Year, and has finished runner-up for the Ballon d\'Or and Best FIFA Men\'s Player.\r\n\r\nAfter beginning his professional career with Groningen, Van Dijk moved to Celtic in 2013, where he won the Scottish Premiership and was named in the PFA Scotland Team of the Year in both of his seasons with the club, also winning the Scottish League Cup in the latter. In 2015, he joined Southampton before signing for Liverpool in January 2018 for £75 million, a then-world-record transfer fee for a defender. With Liverpool, Van Dijk reached back-to-back UEFA Champions League finals in 2018 and 2019, winning the latter. He was also named PFA Players\' Player of the Year and the Premier League Player of the Season in his first full season. Van Dijk later won the FIFA Club World Cup and UEFA Super Cup, and helped end the club\'s 30-year league title drought by winning the 2019–20 Premier League.', 5),
(13, 'Bukayo Saka', 'https://i.guim.co.uk/img/media/2c3a60d6a137a0882798befdb701be6ac20cec24/230_36_2639_1584/master/2639.jpg?width=465&quality=45&auto=format&fit=max&dpr=2&s=31a7127968e50cde3819363d14ca2f59', 7, 'Bukayo Ayoyinka T. M. Saka (born 5 September 2001) is an English professional footballer who plays as a winger, left-back or midfielder for Premier League club Arsenal and the England national team.', 3),
(14, 'Emile Smith-Rowe', 'https://eu-images.contentstack.com/v3/assets/bltcc7a7ffd2fbf71f5/blta21af3565c959cd3/60da733c20a5380ed19eb928/9c7e0c3c74954d15751999abab8ba72c4856d948.jpg?quality=60&w=1000', 10, 'Emile Smith Rowe (born 28 July 2000) is an English professional footballer who plays as an attacking midfielder or winger for Premier League club Arsenal and the England national team.\r\n\r\nSmith Rowe began his senior club playing career with Arsenal in 2018, but sporadic playing time led to loans to Bundesliga\'s RB Leipzig and Huddersfield Town. He established himself as a key player at Arsenal in the following years.\r\n\r\nSmith Rowe represented England\'s youth teams at international level, and won the FIFA U-17 World Cup.', 3),
(15, 'Gabriel Martinelli', 'https://cdn.vox-cdn.com/thumbor/KXMqyRhJhlS5loo8_gKVAHalHk8=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/22771622/1318936285.jpg', 35, 'Gabriel Teodoro Martinelli Silva (born 18 June 2001) is a Brazilian professional footballer who plays as a forward for Premier League club Arsenal. Martinelli began his senior club career playing for Ituano, prior to signing for English club Arsenal in July 2019, aged 18, and won the FA Cup in his debut season.\r\n\r\nAt international level, Martinelli represents the Brazil under-23s. He helped Brazil win an Olympic Gold in men\'s football at the 2020 Summer Olympics.', 3),
(16, 'Thomas Partey', 'https://imgresizer.eurosport.com/unsafe/1200x0/filters:format(jpeg):focal(1626x202:1628x200)/origin-imgresizer.eurosport.com/2021/12/06/3267219-66861648-2560-1440.jpg', 5, 'Thomas Teye Partey (born 13 June 1993) is a Ghanaian professional footballer who plays as a midfielder for Premier League club Arsenal and the Ghana national team.\r\n\r\nPartey began his professional career at Spanish club Atlético Madrid in 2013, going on loan to Mallorca and Almería, and returned to Atlético in 2015, with whom he won the UEFA Europa League and UEFA Super Cup in 2018. In 2020, he joined Arsenal in a transfer worth £45 million (€50 million), becoming the most expensive Ghanaian player of all time.\r\n\r\nA Ghanaian international, Partey represented his nation at two Africa Cup of Nations tournaments. He was named into the CAF Team of the Year in 2018, and won Ghana Player of the Year in 2018 and 2019.', 3),
(17, 'Kevin De Bruyne', 'https://www.mancity.com/meta/media/unqau0vg/kevin-de-bruyne.jpg', 17, 'Kevin De Bruyne (born 28 June 1991) is a Belgian professional footballer who plays as a midfielder for Premier League club Manchester City and the Belgium national team. De Bruyne is widely regarded as one of the best midfielders of his generation and he has often been described as a \"complete footballer\".\r\n\r\nDe Bruyne began his career at Genk, where he was a regular player when they won the 2010–11 Belgian Pro League. In 2012, he joined English club Chelsea, where he was used sparingly and then loaned to Werder Bremen. He signed with Wolfsburg for £18 million in 2014, where he established himself as one of the best players in the Bundesliga and was integral in the club\'s 2014–15 DFB-Pokal win. In the summer of 2015, De Bruyne joined Manchester City for a club record £54 million. He has since won three Premier League titles, five League Cups and an FA Cup with the club. In 2017–18, he had a significant role in Manchester City\'s record in becoming the only Premier League team to attain 100 points in a single season. In 2019–20, De Bruyne tied the record for most assists in a Premier League season and was awarded Player of the Season.\r\n\r\nDe Bruyne made his full international debut in 2010, and he has since earned over 80 caps and scored 23 goals for Belgium. He was a member of the Belgian squads that reached the quarter-finals both at the 2014 FIFA World Cup and at UEFA Euro 2016. He represented Belgium at the 2018 FIFA World Cup, where Belgium won the third place play-off match against England, and was named in the FIFA World Cup Dream Team.', 4),
(18, 'Bernardo Silva', 'https://i2-prod.manchestereveningnews.co.uk/incoming/article22094003.ece/ALTERNATES/s615/2_GettyImages-1351665276.jpg', 20, 'Bernardo Mota Veiga de Carvalho e Silva (born 10 August 1994), known as Bernardo Silva or simply Bernardo, is a Portuguese professional footballer who plays as an attacking midfielder or a winger for Premier League club Manchester City and the Portugal national team. Considered as one of the best midfielders in the world, Silva is known for his dribbling, passing, shooting and work rate.\r\n\r\nBorn in Lisbon, Silva came through Benfica\'s youth academy. He began playing for Benfica B in 2013 and was promoted to the first-team in 2014, playing a few minutes with the latter. He was on loan at the Ligue 1 side Monaco during the 2014–15 season, with Les Monégasques making the move permanent in winter 2015. After winning the league title with them in 2017, he was signed by English club Manchester City for a reported fee of £43.5 million. He subsequently won the Premier League and EFL Cup in his first season in England, following this up with a domestic treble the following season. He had a significant role in City becoming the first men\'s team in England to win a domestic treble, being named Manchester City\'s Player of the Year in 2019 and being part of the PFA Premier League Team of the Year. Afterwards, Silva was listed among the 30-man shortlist for the Ballon d\'Or. In 2020–21, he had a significant role on Manchester City reaching their first UEFA Champions League final.\r\n\r\nSilva made his senior debut for Portugal in 2015 after previously being capped by the nations\'s youth teams at under-19 and under-21 levels. He was chosen in Portugal\'s squads for the 2017 FIFA Confederations Cup, 2018 FIFA World Cup, 2019 UEFA Nations League Finals and UEFA Euro 2020, winning the 2019 tournament on home soil while also being named as the Player of the Tournament.', 4),
(19, 'Riyad Mahrez', 'https://i2-prod.mirror.co.uk/incoming/article23084545.ece/ALTERNATES/s1200c/2_Premier-League-Manchester-City-v-Burnley.jpg', 26, 'Riyad Karim Mahrez (born 21 February 1991) is a professional footballer who plays as a winger for Premier League club Manchester City and captains the Algeria national team.\r\n\r\nMahrez began his career as a youth player for French club AAS Sarcelles. He turned professional in 2009 with Quimper, where he played for only one season before moving to Le Havre, spending a total of three years with them, initially playing for their reserve team and then becoming a first-team regular. In January 2014, Mahrez signed for English side Leicester City, helping them win the Championship and promotion to the Premier League at the end of his first season. In the 2015–16 season he was the Algerian Footballer of the Year, the PFA Players\' Player of the Year, and was a member of the Premier League PFA Team of the Year as he helped Leicester City win the Premier League. He signed for Manchester City in 2018, winning the Premier League, FA Cup and EFL Cup in his first season.\r\n\r\nBorn in France, Mahrez made his international debut for Algeria in 2014 and represented them at the 2014 FIFA World Cup and at the 2015, 2017 and 2019 Africa Cup of Nations, winning the African Cup of Nations in 2019. In 2016 he was named CAF\'s African Footballer of the Year.', 4),
(20, 'Joao Cancelo', 'https://i2-prod.manchestereveningnews.co.uk/incoming/article19788168.ece/ALTERNATES/s615/0_GettyImages-1298712446.jpg', 27, 'João Pedro Cavaco Cancelo (born 27 May 1994) is a Portuguese professional footballer who plays either as a right back, left back or right winger for Premier League club Manchester City and the Portugal national team. He is regarded as one of the best full-backs in the world.\r\n\r\nAfter coming through Benfica\'s youth academy, Cancelo began playing for the club\'s reserve side in 2012 and was promoted to the first team two years later. He was subsequently loaned to La Liga club Valencia during the 2014–15 season, with Los Ches making the move permanent in the summer of 2015. Cancelo was on loan to Serie A team Inter Milan during the 2017–18 season, in which he was included in Serie A\'s Team of the Year. Cancelo\'s performances sparked the interest of Italian rivals Juventus, who signed him in 2018 for a reported fee of €40.4 million. During his stint with Bianconeri, Cancelo won the league and the Supercoppa Italiana in his first and only season. In 2019, he was signed by English club Manchester City, for a reported fee of €65 million (£60 million). He has since won a Premier League title and a League Cup with the club. In 2020–21, he had a significant role in Manchester City reaching their first UEFA Champions League final.\r\n\r\nCancelo made his senior debut for Portugal in 2016 after previously being capped by the nations\'s all youth team levels, winning 75 caps and scoring three goals overall. He was also part of Portugal\'s under-21 team that reached the 2015 UEFA European Championship Final. He was chosen in Portugal\'s squad for the 2019 UEFA Nations League Finals on home soil, winning the inaugural edition of the competition with his nation.\r\n\r\n', 4),
(21, 'Jamie Vardy', 'https://pbs.twimg.com/media/EokUFbuXMAAPyo-.jpg', 9, 'Jamie Richard Vardy (born 11 January 1987) is an English professional footballer who plays as a striker for Premier League club Leicester City. Vardy has also played for the England national team.\r\n\r\nAfter being released by Sheffield Wednesday at the age of 16, Vardy began his senior career with Stocksbridge Park Steels, breaking into the first team in 2007 and spending three seasons there before joining Northern Premier League club FC Halifax Town in 2010. Scoring 25 goals in his debut season, he won the club\'s \"Players\' Player of the Year\" award and then moved to Conference Premier club Fleetwood Town in August 2011 for an undisclosed fee. He scored 31 league goals in his first season at his new team, winning the team\'s \"Player of the Year\" award as they won the division.\r\n\r\nVardy signed for Leicester City in the Championship in May 2012 for a non-League record transfer fee of £1 million and helped the team win the Championship in 2014. In the 2015–16 Premier League season, he scored in eleven consecutive Premier League matches, breaking Ruud van Nistelrooy\'s record, and was voted the Premier League Player of the Season and FWA Footballer of the Year as outsiders Leicester won the title. He won the Premier League Golden Boot for the 2019–20 season, becoming the oldest player to win the award. By playing in the 2021 FA Cup Final, he became the first ever player to play in every round of the competition, from the preliminary stages to the final. Vardy made his international debut in June 2015 and was selected for UEFA Euro 2016 and the 2018 FIFA World Cup.', 6),
(22, 'Youri Tielemans', 'https://i2-prod.leicestermercury.co.uk/sport/football/football-news/article6113329.ece/ALTERNATES/s1200c/0_Youri-Tielemans.jpg', 8, 'Youri Marion A. Tielemans (born 7 May 1997) is a Belgian professional footballer who plays as a midfielder for Premier League club Leicester City and for the Belgium national team.\r\n\r\nTielemans began his career at Anderlecht, where he made 185 official appearances and scored 35 goals across four seasons. He won the league title twice and in 2017 was chosen as the Belgian Professional Footballer of the Year. He is the youngest Belgian to play in the UEFA Champions League, making his debut in the competition at the age of 16 years and 148 days. After two years at Monaco in Ligue 1, he joined Leicester in 2019, initially on loan and then for an estimated fee of £32 million. He scored the only goal of the 2021 FA Cup Final.\r\n\r\nTielemans represented Belgium at several youth levels and before gaining his first cap for the national team in November 2016, aged 19. He was part of the squad that came third at the 2018 FIFA World Cup, also featuring at UEFA Euro 2020.', 6),
(23, 'James Maddison', 'https://images2.minutemediacdn.com/image/fetch/w_736,h_485,c_fill,g_auto,f_auto/https%3A%2F%2Fthetopflight.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2018%2F08%2F1348679038-850x560.jpeg', 10, 'James Daniel Maddison (born 23 November 1996) is an English professional footballer who plays as an attacking midfielder for Premier League club Leicester City and the England national team.\r\n\r\nMaddison began his career with Coventry City before joining Norwich City in 2016. He spent the 2016–17 season on loan at Scottish Premiership club Aberdeen. In his first season back at Norwich, Maddison was named in the Championship PFA Team of the Year and EFL Team of the Season. He joined Premier League club Leicester City in 2018.\r\n\r\nMaddison made his England under-21 debut in the 2019 UEFA European Under-21 Championship qualification and was called up to the senior team in 2019.', 6),
(24, 'Kasper Schmeichel', 'https://upload.wikimedia.org/wikipedia/commons/5/51/Kasper_Schmeichel_2021_vs_Spartak_Moscow.jpg', 1, 'Kasper Peter Schmeichel (pronounced [born 5 November 1986) is a Danish professional footballer who plays as a goalkeeper for Premier League club Leicester City and the Denmark national team. He is the son of former Manchester United and Danish international goalkeeper Peter Schmeichel.\r\n\r\nSchmeichel began his career with Manchester City, but he had loan spells with Darlington, Bury and Falkirk before he made his Manchester City debut. Although Schmeichel appeared to have made the City number 1 jersey his own at the start of the 2007–08 season, the emergence of Joe Hart resulted in Schmeichel being loaned to Cardiff City. The signing of Republic of Ireland international Shay Given in January 2009 meant that Schmeichel fell even further down the pecking order at City, and in August 2009, he was allowed to link up with former manager Sven-Göran Eriksson at Notts County. He spent only one season with the Magpies as, while it was a very successful one for the club and the player himself, changes to the club\'s financial position made his departure necessary and his contract was terminated by mutual consent. He joined Leeds United in May 2010, but again, his tenure at the club would only last one season before he was the subject of a transfer to Leicester City, where he would again work under Eriksson. Schmeichel has gone on to play over 400 competitive games for Leicester, winning the Championship in the 2013–14 season, the Premier League in 2015–16 and the FA Cup in 2020–21.', 6);

-- --------------------------------------------------------

--
-- Table structure for table `teams`
--

CREATE TABLE `teams` (
  `team_id` int(3) NOT NULL,
  `team_name` varchar(255) NOT NULL,
  `description` longtext NOT NULL,
  `image` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `teams`
--

INSERT INTO `teams` (`team_id`, `team_name`, `description`, `image`) VALUES
(1, 'Manchester United', 'Manchester United is one of the most prestigious football clubs and has always maintained a distinguished tradition, a record of consistent success, and a great history. They are together with Liverpool, England\'s most successful football clubs ever. \"The Red Devils\" have more national titles than Liverpool, with a combined 66 trophies to Liverpool\'s 64.', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/640px-Manchester_United_FC_crest.svg.png'),
(2, 'Chelsea', 'While Chelsea were a reasonably consistent club for most of their history, people nowadays usually associate them with the football juggernaut they\'ve become at the turn of the century; not much of a surprise, considering the club won the majority of their silverware in that period. Chelsea have won League titles, FA Cups and League Cups. They\'ve also found success in Europe, becoming the only British club to win all three major UEFA trophies: the Cup Winners\' Cup, the Champions League and the Europa League.', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/1200px-Chelsea_FC.svg.png'),
(3, 'Arsenal', 'As one of the most successful and beloved clubs in England, Arsenal Football Club was always a magnet for the public. Tradition-wise, their results speak for themselves; in addition to winning 28 major domestic trophies, Arsenal hold the records for longest unbeaten streak and longest run in top flight of English football.', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/800px-Arsenal_FC.svg.png'),
(4, 'Manchester City', 'Much like their Mancunian rivals, Manchester City have seen many highs during their colorful existence. With First Division/Premier League titles, FA Cups, League Cups and one Cup Winners\' Cup, City stand tall as one of the most successful English football clubs of all time. Still, their history contains more than enough lows to even it up; for example, City are still the only English champions to be relegated the very next season.', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png'),
(5, 'Liverpool', 'Since they were founded in 1892, the Liverpool Football Club name was synonymous with fame and glory. Internationally, Liverpool is the most successful British club of all time with plenty of European trophies on their record. They are one of the most popular football teams in the world, with over 200 supporter clubs in at least 50 different countries. And yet, their magnificent history will forever be plagued by two of the worst stadium disasters of all time: Heysel and Hillsborough.', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/800px-Liverpool_FC.svg.png'),
(6, 'Leicester City', 'While Leicester City does not have as colorful a history as some of their Midlands rivals, the club can boast of spending only a single season outside the top two divisions of English football. They have won several Second Division titles and three League Cups, and being responsible for finishing first in the Premier League against all odds in 2016. Leicester is known for their long-standing rivalry with Nottingham Forest, a feature usually referred to as the East Midlands derby. In the club\'s past, two of England’s most legendary goalkeepers, Gordon Banks and Peter Shilton, have been protecting the net.', 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/Leicester_City_crest.svg/1200px-Leicester_City_crest.svg.png');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `player`
--
ALTER TABLE `player`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_team_id` (`team_id`);

--
-- Indexes for table `teams`
--
ALTER TABLE `teams`
  ADD PRIMARY KEY (`team_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `player`
--
ALTER TABLE `player`
  MODIFY `id` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;

--
-- AUTO_INCREMENT for table `teams`
--
ALTER TABLE `teams`
  MODIFY `team_id` int(3) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `player`
--
ALTER TABLE `player`
  ADD CONSTRAINT `fk_team_id` FOREIGN KEY (`team_id`) REFERENCES `teams` (`team_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
